"""tabelas

Revision ID: 65fca91dfbbb
Revises: 14c171f6b9cd
Create Date: 2025-07-17 18:34:46.372571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65fca91dfbbb'
down_revision: Union[str, Sequence[str], None] = '14c171f6b9cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_favorite_recipes',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('recipe_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'recipe_id')
    )
    op.add_column('recipes', sa.Column('is_public', sa.Boolean(), nullable=False))
    op.drop_index(op.f('ix_recipes_id'), table_name='recipes')
    op.drop_column('recipes', 'img_url')
    op.drop_column('recipes', 'category')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('recipes', sa.Column('img_url', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_recipes_id'), 'recipes', ['id'], unique=False)
    op.drop_column('recipes', 'is_public')
    op.drop_table('user_favorite_recipes')
    # ### end Alembic commands ###
